/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package proyectocalculadora.u2.views;

import java.awt.Color;
import java.awt.Graphics;

/**
 *
 * @author claua
 */
public class Grafica extends javax.swing.JPanel {

    static int ancho = 460, alto = 380;
    static double[] ejeX = new double[ancho];
    static double[] ejeY = new double[ancho];
    static double[] ejeX1 = new double[ancho];
    static double[] ejeY1 = new double[ancho];
    static double[] ejeX2 = new double[ancho];
    static double[] ejeY2 = new double[ancho];

    static int m1 = 0, m2 = 0, m3 = 0, m4 = 0, 
            longitud1 = 0, longitud2 = 0, 
            ejex = 0, ejey = 0;

    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
    }

    //definimos la funcion proncipal con la que se realizara la integral
    static double f (double x){
        double y;
       //y = -((Math.pow(x,3))-(Math.pow(x,2)*6)+(9*x)+5); //limite inferior -3 limite superior 2 https://www.youtube.com/watch?v=wuI5MFhvgsY
       //y = -Math.cos(x);
       //y = -((Math.pow(x,3))-(Math.pow(x,2)*6)+(8*x));
       //y = -Math.sin(x);
       y=Math.pow(x,2);
       return y;
    }
    
    @Override
    public void paint(Graphics g) {
        super.paint(g);

        m1 = -10;
        m2 = 10;
        m3 = 10;
        m4 = -10;

        ejex = (m1) + (m2);
        ejey = (m3) + (m4);

        longitud1 = (int) ancho / (Math.abs(m1) + Math.abs(m2));
        longitud2 = (int) alto / (Math.abs(m3) + Math.abs(m4));

        g.setColor(Color.black);
        g.fillRoundRect(0, 0, ancho, alto, 5, 5);
        g.setColor(Color.white);
        g.fillRoundRect(2, 2, ancho - 4, alto - 4, 3, 3);

        //Lineas horizontales de la cuadricula
        for (int i = 0; i <= ancho; i = i + longitud1) {
            g.setColor(Color.LIGHT_GRAY);
            g.drawLine(i, 0, i, alto);
        }
        //lineas verticales de la cuadricula
        for (int j = 0; j <= alto; j = j + longitud2) {
            g.setColor(Color.LIGHT_GRAY);
            g.drawLine(0, j, ancho, j);
        }
        //Ejes de la grafica
        g.setColor(Color.black);
        g.drawLine(-m2 * longitud1, 0, -m2 * longitud1, alto);
        g.setColor(Color.black);
        g.drawLine(0, m3 * longitud2, ancho, m3 * longitud2);
        
        g.setColor(Color.pink);
        g.drawLine(360, 200, 360, 250); //x, y, x2, y2
        g.drawLine(360, 220, 425, 220);
        
//Grafica la función
        for (int x = 1; x < 457; x++) {
            g.setColor(Color.blue);
            g.drawLine((int)ejeX[x], (int)ejeY[x], (int)ejeX[x+1], (int)ejeY[x+1]);
        }
        
//Grafica la derivada
        for (int i = 1; i < 457; i++) {
            g.setColor(Color.red);
            g.drawLine((int)ejeX1[i], (int)ejeY1[i], (int)ejeX1[i+1], (int)ejeY1[i+1]);
        }
        
        for (int i = 0; i < 457; i++) {
            g.setColor(Color.black);
            g.drawLine((int)ejeX2[i], alto/2, (int)ejeX2[i], (int)ejeY2[i]);
            i++;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "GRAFICA"));
        setPreferredSize(new java.awt.Dimension(600, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 568, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
